### ISSUE TITLE
Generalize scuttleshell.json path

### ISSUE THREAD

**Issue by staltz** [soapdog/scuttle-shell#1]
I'm not sure what supposed to be this `path`, but I'm quite sure it's not your local directory structure

https://github.com/soapdog/scuttle-shell/blob/851531c0e3ba49e7d6301e1941f7cf92e8f91628/scuttleshell.json#L4

**Comment by soapdog** [comment]
@staltz this value is overwritten by the `postinstall` script. Still, @mixmix made an awesome job and refactored it out. I've just merged his PR.
